b.dofile("graveyard.lua")
b.dofile("hut.lua")
b.dofile("igloo.lua")
b.dofile("lava_pit.lua")
b.dofile("scroll_stash.lua")
b.dofile("loom_eruption.lua")
b.dofile("watchtower.lua")
b.dofile("weave.lua")
